Set a min-version for burn-jit, due to clippy.
At 1.82.0; burn-jit won't compile:
```
   Compiling burn-import v0.16.0 (/home/crutcher/git/burn/burn/crates/burn-import)
error: unknown lint: `clippy::manual_div_ceil`
  --> crates/burn-jit/src/kernel/conv/conv2d/gemm/homogeneous/base.rs:79:17
   |
79 |         #[allow(clippy::manual_div_ceil)]
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::manual_filter`
   |
   = note: `-D unknown-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unknown_lints)]`

error: unknown lint: `clippy::manual_div_ceil`
  --> crates/burn-jit/src/kernel/pool/adaptive_avg_pool2d.rs:65:9
   |
65 | #[allow(clippy::manual_div_ceil)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::manual_filter`

error: unknown lint: `clippy::manual_div_ceil`
  --> crates/burn-jit/src/kernel/pool/adaptive_avg_pool2d_backward.rs:69:9
   |
69 | #[allow(clippy::manual_div_ceil)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::manual_filter`
```

https://github.com/tracel-ai/burn/issues/2569