Bump MSRV to 1.67
On a fresh checkout, users are presented with this error:

error: package `time v0.3.28` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.67.0 or newer, or use
cargo update -p time@0.3.28 --precise ver
where `ver` is the latest version of `time` supporting rustc 1.65.0

The time crate can be downgraded to 0.3.23, but it's not a great experience
out of the box.